[package]
name = "srvbees"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
getopts = "0.2.21"
prometheus-client = "0.23.1"
prometheus-client-derive-encode = "0.4.2"
tokio = {version="1.45.1", features=["full"]}
